### ISSUE TITLE
LGPL License while GEOSwift uses MIT

### ISSUE THREAD

**Issue by forbidden404** [GEOSwift/geos#1]
Hello there,

The GEOSwift library switched to MIT License, but geos still remains with with the LGPL license, while CocoaPods still adds geos to the Acknowledgement file, I wish to know if that's intended, since the main project itself is currently under MIT License.

**Comment by vfn** [comment]
Hi @forbidden404,

I'm not sure if I understood your question.

`GEOS` pod is just a CocoaPods friendly version of https://github.com/OSGeo/geos and it's under LGPL.

`GEOSwift` doesn't modify any of GEOS' code, It uses it as a dependency/library, and it's distributed under MIT.

What's your question/concern?

**Comment by forbidden404** [comment]
`GEOS` is brought to the dependencies in an iOS project with `GEOSwift`, the latter being distributed under MIT. Having a LGPL package under the App Bundle of an application wouldn't make it necessary to provide the necessary project files so the requesting user can recompile the project with any `GEOS` version they choose to? It's more of an issue about of how much influence the LGPL license under `GEOS` would have in any possible liabilities for having that in the project.

If it's something not doable (since you said `GEOS` is just a CocoaPods friendly version of a library under LGPL), I understand. During the process of getting an application ready for release, I came up with the LGPL license under the Acknowledgements file from CocoaPods and that was worrying, even though the license isn't the GPL 2.1. 

I could be completely wrong about the influence a LGPL license could have on that, since I'm providing the license for all third-party libraries used in the application, I'm not that well informed about the influences LGPL could possibly have, other than reading about being discouraged to be used in iOS applications, not as much as the GPL though.

**Comment by vfn** [comment]
I see what you mean. That's is not an issue for `GEOSwift` itself, but it might be an issue for an app you build for distribution.

You'd need to consult a layer to determine whether you can use it or not on your project, and what you should do to comply if you decide to use it

**Comment by forbidden404** [comment]
Thank you for the information, I will be removing the library for the time being, but thanks for the clarification, in any case, great work you guys are doing!
