### ISSUE TITLE
Update to libgeos/geos 3.11.0

### ISSUE THREAD

**Issue by vladislavitsi** [GEOSwift/geos#20]
Hi,

Currently the latest version of GEOSwift is based on libgeos/geos 3.10.1 
The new version of  libgeos/geos 3.11 from July 1 2022 introducing ConcaveHull, which is very useful for many cases when ConvexHull is not sufficient.

Is there any time estimates on when the new version might be released?
That would be very helpful :)

**Comment by macdrevx** [comment]
related to https://github.com/GEOSwift/GEOSwift/issues/256
